### ISSUE TITLE
Extruding multiple faces at once behaves unintuitively

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/open-blocks#41]
Steps to reproduce:

1. Create a sphere
2. Switch to the modify tool and select several adjacent faces
3. Extrude them while holding the left trigger to enable "snapping mode"

Expected behaviour: each face should extrude by the same amount

Actual behaviour: faces extrude by different amounts

I suspect the mount of extrusion for each face is based on a vector to the primary faces position (or something like that)

**Comment by andybak** [comment]
@naam00 - thoughts?

**Comment by naam00** [comment]
Ah sirry didn't see this one. Yes, thoughts! Played with it, it leads to an issue, see Issues:
https://github.com/icosa-foundation/open-blocks/issues/43
(I'll just press comment, not reopen with comment, hope that works)
